export const ClientsData = [
  {
    image: '/images/client19.jpg',
    url: 'https://music.apple.com/us/album/experience-israeli-and-jewish-culture/449970191',
    title: 'Experience Israeli and Jewish Culture',
    artist: 'The Shuk',
  },
  {
    image: '/images/client20.jpg',
    url: 'https://southronrancor1.bandcamp.com/releases',
    title: 'cynosure',
    artist: 'southron rancor',
  },
  {
    image: '/images/client15.jpg',
    url: 'https://walkerfarrell.bandcamp.com/album/music-for-0-musicians-2022-remaster',
    title: 'Music for 0​.​∞ Musicians (2022 Remaster)',
    artist: 'Walker Farrell',
  },
  {
    image: '/images/client22.jpg',
    url: 'https://thevoltperoctaves.com/albums/',
    title: 'Sleeping In',
    artist: 'The Volt Per Octaves',
  },
  {
    image: '/images/client23.jpg',
    url: 'https://www.youtube.com/watch?v=CELrul5Xld0',
    title: 'Leave You Tonight',
    artist: 'Taylor Aaron Parker Williams',
  },
  {
    image: '/images/client2.jpg',
    url: 'https://xibalba.bandcamp.com/album/oblation',
    title: 'Oblation',
    artist: 'Depuratus, Espiritus',
  },
  {
    image: '/images/client1.jpg',
    url: 'https://mindspringmusic.bandcamp.com/album/cloudburst-compiled-by-kri-samadhi',
    title: 'Cloudburst - Compiled By: Kri Samadhi',
    artist: 'VA - Various Artists',
  },
  {
    image: '/images/client3.jpg',
    url: 'https://xibalba.bandcamp.com/album/idris-and-friends',

    title: 'Idris And Friends',
    artist: 'Idris',
  },
  {
    image: '/images/client4.jpg',
    url: 'https://xibalba.bandcamp.com/album/embracing-of-darkness',
    title: 'Embracing of Darkness',
    artist: 'Xydur',
  },
  {
    image: '/images/client5.jpg',
    url: 'https://xibalba.bandcamp.com/album/robots',
    title: 'Robots',
    artist: 'Kaikkialla',
  },
  {
    image: '/images/client6.jpg',
    url: 'https://xibalba.bandcamp.com/album/tabur-and-friends',
    title: 'Taburá and Friends',
    artist: 'Taburá',
  },
  {
    image: '/images/client7.jpg',
    url: 'https://xibalba.bandcamp.com/album/ganapathie',
    title: 'Ganapathie',
    artist: 'Magnetik Sadhu',
  },
  {
    image: '/images/client8.jpg',
    url: 'https://brahmasutrarecords.bandcamp.com/album/va-if-the-demon-has-a-club',
    title: 'VA 鬼​に​金​棒 IF THE DEMON HAS A CLUB',
    artist: 'DJ Yuji Ledesma',
  },
  {
    image: '/images/client9.jpg',
    url: 'https://starseedpsytrance.bandcamp.com/album/dreamweaver',
    title: 'Dreamweaver',
    artist: 'Oneiros Project',
  },
  {
    image: '/images/client10.jpg',
    url: 'https://brahmasutrarecords.bandcamp.com/album/the-reborn',
    title: 'The Reborn',
    artist: 'Malinalli',
  },
  {
    image: '/images/client11.jpg',
    url: 'https://darkdimensionrecords.bandcamp.com/album/anhedonia-ep-by-n-n',
    title: 'Anhedonia Ep by N, N',
    artist: 'NN',
  },
  {
    image: '/images/client12.jpg',
    url: 'https://starseedpsytrance.bandcamp.com/album/rising-serpents',
    title: 'Rising Serpents',
    artist: 'Kukulkan',
  },
  {
    image: '/images/client13.jpg',
    url: 'https://karmatec-records.bandcamp.com/track/--9',
    title:
      '𝐊​𝐫​𝐢 𝐒​𝐚​𝐦​𝐚​𝐝​𝐡​𝐢 & 𝐂​𝐨​𝐬​𝐦​𝐢​𝐜 𝐁​𝐫​𝐚​𝐡​𝐦​𝐚 - 𝘼​𝙣​𝙖​𝙡​𝙤​𝙜 𝙆​𝙖​𝙧​𝙢​𝙖',
    artist: 'M​Ɩ​Ɲ​Ɗ Ƴ​Ơ​Ʋ​Ʀ Ƙ​ƛ​Ʀ​Mƛ by Karmatec Records',
  },
  {
    image: '/images/client14.jpg',
    url: 'https://xibalba.bandcamp.com/album/spiritual-gangsters',
    title: 'Spiritual Gangsters',
    artist: 'Brejo Project',
  },
  {
    image: '/images/client21.jpg',
    url: 'https://thevoltperoctaves.com/albums/',
    title: 'Joining The Circuits',
    artist: 'The Volt Per Octaves',
  },
  {
    image: '/images/client16.jpg',
    url: 'https://brahmasutrarecords.bandcamp.com/album/va-growling-forest-4',
    title: 'VA Growling Forest 4',
    artist: 'Groovemoon',
  },
  {
    image: '/images/client17.jpg',
    url: 'https://voodoo-hoodoo.bandcamp.com/album/v-a-jungle-jingles-compiled-by-high-technician-forest',
    title: 'V​/​A JUNGLE JINGLES compiled by High​-​Technician [Forest]',
    artist: 'Various Artists',
  },
  {
    image: '/images/client18.jpg',
    url: 'https://tonyrolando.bandcamp.com/track/vaaaaanished',
    title: 'Vaaaaanished',
    artist: 'Tony Rolando',
  },
  {
    image: '/images/client24.jpg',
    url: 'https://touchsamadhi.bandcamp.com/album/infinite-moments',
    title: 'Infinite Moments',
    artist: 'Kri Samadhi',
  },
];
